INSERT INTO `combo_master_data` (`id`, `combo_name`, `combo_key`, `combo_value`)
VALUES
(1, 'TRANSACTION_TYPE', 'CASH', 'CASH'),
(2, 'TRANSACTION_TYPE', 'CHEQUE', 'CHEQUE'),
(3, 'TRANSACTION_TYPE', 'BANK TRANSFER', 'BANK TRANSFER'),
(4, 'TRANSACTION_TYPE', 'WALLET', 'WALLET'),
(5, 'TRANSACTION_TYPE', 'DD', 'DD'),
(6, 'TRANSACTION_TYPE', 'CREDIT CARD', 'CREDIT CARD'),
(7, 'FINE_TYPE', 'LATE FEE', 'LATE FEE'),
(8, 'FINE_TYPE', 'ATTENDENC FINE', 'ATTENDANCE FINE'),
(9, 'FINE_TYPE', 'PROPERTY DAMAGE FINE', 'PROPERTY DAMAGE FINE');
